theme: jekyll-theme-cayman
title: Face Landmark-based Speaker-Independent Audio-Visual Speech Enhancement in Multi-Talker Environments
description: Giovanni Morrone, Luca Pasa, Vadim Tikhanoff, Sonia Bergamaschi, Luciano Fadiga, Leonardo Badino
University of Modena and Reggio Emilia
Istituto Italiano di Tecnologia
